In [1]:
import pandas as pd
import numpy as np
from scipy.linalg import inv
import matplotlib.pyplot as plt

In [2]:
houses = pd.read_csv("C:\\Users\\HA432CU\\Machine Learning\\Linear Regression\\Housing.csv")

In [41]:
def mahalanobis_distance(dataframe, dataframe_columns, threshold):
    # Convert dataframe columns to a numpy array
    np_array_dataframe_columns = dataframe[dataframe_columns].values
    
    # Calculate mean of the columns
    np_mean_dataframe_columns = np.mean(np_array_dataframe_columns, axis=0)
    
    # Calculate covariance matrix of the columns
    np_cov_dataframe_columns = np.cov(np_array_dataframe_columns, rowvar=False)
    
    distances = []
    
    # Calculate Mahalanobis Distances for each data point
    for _, row in dataframe.iterrows():
        data_point = row[dataframe_columns].values
    
        # Calculate Mahalanobis Distance
        diff = data_point - np_mean_dataframe_columns
        inv_covariance_matrix = inv(np_cov_dataframe_columns)
        mahalanobis_distance = np.sqrt(np.dot(np.dot(diff, inv_covariance_matrix), diff.T))
    
        distances.append(mahalanobis_distance)

    # distances now contains the Mahalanobis distances for each data point
    mahalanobis_series = pd.Series(distances, name='Mahalanobis Distance')
    
    # Set a Mahalanobis Distance threshold
    mahalanobis_threshold = threshold
    
    # Identify and exclude outliers
    outliers_mask = mahalanobis_series > mahalanobis_threshold
    filtered_data = dataframe[~outliers_mask]
    outliers = dataframe[outliers_mask]
    
    # Display the results
    print("Original Data:")
    print(dataframe)
    print("\nData excluding outliers:")
    print(filtered_data)
    print("\nOutliers:")
    print(outliers)

In [42]:
# Example usage:
# Assuming 'houses' is your dataframe and ['price', 'area'] are the columns of interest
mahalanobis_distance(houses, ['price', 'area'], 3.0)

Original Data:
        price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no
1    12250000  8960         4          4        4      yes        no       no
2    12250000  9960         3          2        2      yes        no      yes
3    12215000  7500         4          2        2      yes        no      yes
4    11410000  7420         4          1        2      yes       yes      yes
..        ...   ...       ...        ...      ...      ...       ...      ...
540   1820000  3000         2          1        1      yes        no      yes
541   1767150  2400         3          1        1       no        no       no
542   1750000  3620         2          1        1      yes        no       no
543   1750000  2910         3          1        1       no        no       no
544   1750000  3850         3          1        2      yes        no       no

    hotwaterheating airconditioning  parking prefarea furnishingstatus
0                no             yes        2      yes        furnished
1                no             yes        3       no        furnished
2                no              no        2      yes   semi-furnished
3                no             yes        3      yes        furnished
4                no             yes        2       no        furnished
..              ...             ...      ...      ...              ...
540              no              no        2       no      unfurnished
541              no              no        0       no   semi-furnished
542              no              no        0       no      unfurnished
543              no              no        0       no        furnished
544              no              no        0       no      unfurnished

[545 rows x 13 columns]

Data excluding outliers:
        price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
6    10150000  8580         4          3        4      yes        no       no
8     9870000  8100         4          1        2      yes       yes      yes
11    9681000  6000         4          3        2      yes       yes      yes
12    9310000  6550         4          2        2      yes        no       no
14    9240000  7800         3          2        2      yes        no       no
..        ...   ...       ...        ...      ...      ...       ...      ...
540   1820000  3000         2          1        1      yes        no      yes
541   1767150  2400         3          1        1       no        no       no
542   1750000  3620         2          1        1      yes        no       no
543   1750000  2910         3          1        1       no        no       no
544   1750000  3850         3          1        2      yes        no       no

    hotwaterheating airconditioning  parking prefarea furnishingstatus
6                no             yes        2      yes   semi-furnished
8                no             yes        2      yes        furnished
11              yes              no        2       no   semi-furnished
12               no             yes        1      yes   semi-furnished
14               no              no        0      yes   semi-furnished
..              ...             ...      ...      ...              ...
540              no              no        2       no      unfurnished
541              no              no        0       no   semi-furnished
542              no              no        0       no      unfurnished
543              no              no        0       no        furnished
544              no              no        0       no      unfurnished

[527 rows x 13 columns]

Outliers:
        price   area  bedrooms  bathrooms  stories mainroad guestroom  \
0    13300000   7420         4          2        3      yes        no
1    12250000   8960         4          4        4      yes        no
2    12250000   9960         3          2        2      yes        no
3    12215000   7500         4          2        2      yes        no
4    11410000   7420         4          1        2      yes       yes
5    10850000   7500         3          3        1      yes        no
7    10150000  16200         5          3        2      yes        no
9     9800000   5750         3          2        4      yes       yes
10    9800000  13200         3          1        2      yes        no
13    9240000   3500         4          2        2      yes        no
66    6930000  13200         2          1        1      yes        no
69    6790000  12090         4          2        2      yes        no
125   5943000  15600         3          1        1      yes        no
129   5873000  11460         3          1        3      yes        no
186   5110000  11410         2          1        2      yes        no
211   4900000  12900         3          1        1      yes        no
277   4305000  10360         2          1        1      yes        no
403   3500000  12944         3          1        1      yes        no

    basement hotwaterheating airconditioning  parking prefarea  \
0         no              no             yes        2      yes
1         no              no             yes        3       no
2        yes              no              no        2      yes
3        yes              no             yes        3      yes
4        yes              no             yes        2       no
5        yes              no             yes        2      yes
7         no              no              no        0       no
9         no              no             yes        1      yes
10       yes              no             yes        2      yes
13        no             yes              no        2       no
66       yes             yes              no        1       no
69        no              no              no        2      yes
125       no              no             yes        2       no
129       no              no              no        2      yes
186       no              no              no        0      yes
211       no              no              no        2       no
277       no              no              no        1      yes
403       no              no              no        0       no

    furnishingstatus
0          furnished
1          furnished
2     semi-furnished
3          furnished
4          furnished
5     semi-furnished
7        unfurnished
9        unfurnished
10         furnished
13         furnished
66         furnished
69         furnished
125   semi-furnished
129   semi-furnished
186        furnished
211        furnished
277   semi-furnished
403      unfurnished